In [52]:
import numpy as np
import pandas as pd
import statistics as stts

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

### 1.Import data

In [53]:
data = pd.read_csv('../data/data_cleaned.csv')

X, y = data.drop('Survived', axis=1), data.pop('Survived')

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, stratify=y)

### 2. Define a baseline

In [54]:
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

clf.score(X_train, y_train), clf.score(X_test, y_test)

(0.9887640449438202, 0.75)

### 3. Create a model

In [55]:
RFC = RandomForestClassifier(n_estimators=500, max_depth=12)
RFC.fit(X_train, y_train)

RandomForestClassifier(max_depth=12, n_estimators=500)

In [56]:
RFC.score(X_train, y_train), RFC.score(X_test, y_test)

(0.9614767255216693, 0.8283582089552238)

In [58]:
X_train

,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Sex_female,Sex_male,SibSp_0,SibSp_1,SibSp_2,...,Parch_0,Parch_1,Parch_2,Parch_3,Parch_4,Parch_5,Parch_6,Embarked_C,Embarked_Q,Embarked_S
463,48.000000,13.0000,0,1,0,0,1,1,0,0,...,1,0,0,0,0,0,0,0,0,1
29,29.699118,7.8958,0,0,1,0,1,1,0,0,...,1,0,0,0,0,0,0,0,0,1
401,26.000000,8.0500,0,0,1,0,1,1,0,0,...,1,0,0,0,0,0,0,0,0,1
665,32.000000,73.5000,0,1,0,0,1,0,0,1,...,1,0,0,0,0,0,0,0,0,1
302,19.000000,0.0000,0,0,1,0,1,1,0,0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,5.000000,31.3875,0,0,1,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
559,36.000000,17.4000,0,0,1,1,0,0,1,0,...,1,0,0,0,0,0,0,0,0,1
244,30.000000,7.2250,0,0,1,0,1,1,0,0,...,1,0,0,0,0,0,0,1,0,0
788,1.000000,20.5750,0,0,1,0,1,0,1,0,...,0,0,1,0,0,0,0,0,0,1
231,29.000000,7.7750,0,0,1,0,1,1,0,0,...,1,0,0,0,0,0,0,0,0,1

In [57]:
pd.Series(RFC.feature_importances_)

0     0.235414
1     0.216850
2     0.024752
3     0.020757
4     0.050170
5     0.157119
6     0.148423
7     0.018292
8     0.016237
9     0.005918
10    0.009253
11    0.005588
12    0.001336
13    0.003042
14    0.017041
15    0.013278
16    0.011003
17    0.000701
18    0.003184
19    0.001916
20    0.000000
21    0.014213
22    0.008685
23    0.016825
dtype: float64